name: Developing

env:
  SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  PRODUCTION_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
  PRODUCTION_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        with:
          node-version: ${{ matrix.node-version }}
#      - run: |
#          apt-get update
#          apt-get install --yes --no-install-recommends postgresql-client
      - run: cd web && npm install
      - run: cd web && npm run prisma:db-push
      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/seed.sql
      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/auth_fix.sql
      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/auth_triggers.sql
