name: FROSHIT CI

env:
  NEXT_PUBLIC_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_DATABASE_URL }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  PRODUCTION_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}
  PRODUCTION_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd web && npm install supabase prisma
      - run: cd web && npm run prisma:db-push
#      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/seed.sql
      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/auth_fix.sql
      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/auth_triggers.sql
      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/add_realtime_tables.sql
      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/storage_policies.sql
      - run: cd web && npx supabase functions deploy onboard-university --project-ref mybvkrkmvnuzeqvzgbzg
      - run: cd web && npx supabase functions deploy onboard-froshee --project-ref mybvkrkmvnuzeqvzgbzg --no-verify-jwt
      - run: PGPASSWORD=$PRODUCTION_DB_PASSWORD psql -h db.mybvkrkmvnuzeqvzgbzg.supabase.co -p 5432 -d postgres -U postgres -f web/supabase/scripts/auth_fix.sql
